Add manual deployment guide for Azure
scalar-labs/scalar-kubernetes pull request #130
Opened 2021-06-16 05:29 UTC by mathewseby

Create a manual deployment guide for Scalar DL on Azure

This is a manual deployment guide for scalar DL in Azure. We hope this guide will be used by people with basic knowledge of Azure and AKS, so this guide does not include step-by-step deployment procedures. With this guide, users can create production and development environments based on their convenience and deploy Scalar DL and configure the monitor services.

2021-06-16 07:01 UTC, feeblefakie requested changes

2021-06-16 07:01 UTC, feeblefakie commented on docs/SetupAzureDatabase.md
> +You need to create a Cosmos DB account for Scalar DL. In this section, you will set up a Cosmos DB for Scalar DL.
```suggestion
In this section, you will set up a Cosmos DB for Scalar DL.
```

2021-06-16 18:57 UTC, mathewseby commented on docs/ManualDeploymentGuideScalarDLonAzure.md
> +### Procedures
Changed all `Procedures` headings to `Steps`

2021-06-16 18:58 UTC, mathewseby commented on docs/ManualDeploymentGuideScalarDLonAzure.md
> +[Create an Azure virtual network](https://docs.microsoft.com/en-us/azure/virtual-network/quick-create-portal) with the above requirements and recommendations along with your organizational or applica
Updated links accordingly. Also changed steps to bullet points in 4c18add.

2021-06-16 18:59 UTC, mathewseby commented on docs/ManualDeploymentGuideScalarDLonAzure.md
> +* An Azure Virtual Network associated with Resource Group
Sorry, Updated the sentence as per suggestion in 4c18add.

2021-06-16 18:59 UTC, mathewseby commented on docs/ManualDeploymentGuideScalarDLonAzure.md
> +* An AKS cluster with Kubernetes node pool
Sorry, Updated the sentence as per suggestion in 4c18add.

2021-06-16 19:00 UTC, mathewseby commented on docs/ManualDeploymentGuideScalarDLonAzure.md
> +* 1 Bastion instance with a public IP
Changed it to `A bastion instance`

2021-06-16 19:05 UTC, mathewseby commented on docs/ManualDeploymentGuideScalarDLonAzure.md
> +* You must add AKS Service principal as `Network contributor` for the k8s_ingress subnet.
> I can't understand the sentence.

I have updated the sentence in 4c18add

> Why N is capitalized?

Changed it to `Network Contributor` which is the role name in the Azure portal in 4c18add.

2021-06-16 19:10 UTC, mathewseby commented on docs/ManualDeploymentGuideScalarDLonAzure.md
> +* You must create a seperate AKS node pool with the name `scalardlpool` for Scalar DL deployment.
Updated the sentence as `You must create a new user node pool with the name scalardlpool for Scalar DL deployment.`

Fixed in 4c18add

2021-06-16 19:23 UTC, mathewseby commented on docs/ManualDeploymentGuideScalarDLonAzure.md
> +* You must create the Kubernetes cluster with `Service principal` as the Authentication method.
> which Kubernetes cluster? a Kubernetes cluster?

Yes, `a Kubernetes cluster`
Changed it accordingly.

> Why S is capitalized?

Changed it to `service principal`

Fixed in 4c18add

2021-06-16 19:24 UTC, mathewseby commented on docs/ManualDeploymentGuideScalarDLonAzure.md
> +* You must create the Kubernetes cluster with `Azure CNI`.
Fixed in 4c18add

2021-06-16 19:24 UTC, mathewseby commented on docs/ManualDeploymentGuideScalarDLonAzure.md
> +* You should create 3 nodes in each node group for high availability in the production.
Thank you, Fixed in 4c18add

2021-06-16 19:25 UTC, mathewseby commented on docs/ManualDeploymentGuideScalarDLonAzure.md
> +Create an AKS cluster with a node pool to deploy the Scalar DL.
Removed the sentence in 4c18add

2021-06-16 19:26 UTC, mathewseby commented on docs/ManualDeploymentGuideScalarDLonAzure.md
> +After creating the Kubernetes cluster next step is to deploy Scalar DL into the AKS cluster.
Fixed in 4c18add

2021-06-16 19:26 UTC, mathewseby commented on docs/ManualDeploymentGuideScalarDLonAzure.md
> +Install the helm tool on your bastion to deploy helm-charts:
Changed to Helm in 4c18add

2021-06-16 19:26 UTC, mathewseby commented on docs/ManualDeploymentGuideScalarDLonAzure.md
> +* [helm](https://helm.sh/docs/intro/install/): helm command-line tool to manage releases in the AKS cluster. In this tutorial, it is used to deploy Scalar DL and Schema loading helm charts to the AKS
Fixed in 4c18add

2021-06-16 19:30 UTC, mathewseby commented on docs/ManualDeploymentGuideScalarDLonAzure.md
> +1. Download the following Scalar DL configuration files and update the database configuration in `scalarLedgerConfiguration` and `schemaLoading` sections
Specified link to [Configure Scalar DL](https://github.com/scalar-labs/scalar-kubernetes/blob/manual-deployment-guide-for-azure/docs/SetupAzureDatabase.md#configure-scalar-dl) section of database guide in Sentence

2021-06-16 19:31 UTC, mathewseby commented on docs/ManualDeploymentGuideScalarDLonAzure.md
> +* You must configure the database properties in the helm chart custom values file.
Removed the sentence, since there is already a step for it.
Removed in 4c18add

2021-06-16 19:31 UTC, mathewseby commented on docs/ManualDeploymentGuideScalarDLonAzure.md
> +* You must confirm that the replica count of the ledger and envoy pods in the `scalardl-custom-values.yaml` file is equal to the number of nodes in the Scalar DL node pool.
It is a requirement to confirm before deployment, I think it is needed as a requirement.

2021-06-16 19:33 UTC, mathewseby commented on docs/ManualDeploymentGuideScalarDLonAzure.md
> +* You should enable monitoring for AKS in production.
Removed in 4c18add

2021-06-16 19:33 UTC, mathewseby commented on docs/ManualDeploymentGuideScalarDLonAzure.md
> +[Enable monitoring of Azure Kubernetes Service](https://docs.microsoft.com/en-us/azure/azure-monitor/containers/container-insights-enable-existing-clusters).
Updated in 4c18add

2021-06-16 19:36 UTC, mathewseby commented on docs/ManualDeploymentGuideScalarDLonAzure.md
> +* Follow the document to confirm the [Cluster insights](https://docs.microsoft.com/en-us/azure/azure-monitor/containers/container-insights-overview#how-do-i-access-this-feature).
Updated sentence in 4c18add

2021-06-16 19:36 UTC, mathewseby commented on docs/ManualDeploymentGuideScalarDLonAzure.md
> +* Follow the document to confirm the [Monitor Azure Cosmos DB](https://docs.microsoft.com/en-us/azure/cosmos-db/monitor-cosmos-db).
Fixed in 4c18add

2021-06-16 19:36 UTC, mathewseby commented on docs/ManualDeploymentGuideScalarDLonAzure.md
> +* Follow the [Maintain the cluster](./Maintaincluster.md) section for more customization.
Fixed in 4c18add

2021-06-16 19:36 UTC, mathewseby commented on docs/ManualDeploymentGuideScalarDLonAzure.md
> +* [Create an AKS cluster](https://docs.microsoft.com/en-us/azure/aks/kubernetes-walkthrough-portal#create-an-aks-cluster) with the above requirements and recommendations.
Fixed in 4c18add

2021-06-16 19:36 UTC, mathewseby commented on docs/ManualDeploymentGuideScalarDLonAzure.md
> +* You should configure [autoscaling](https://docs.microsoft.com/en-us/azure/aks/cluster-autoscaler) for the AKS cluster.
Fixed in 4c18add

2021-06-16 19:36 UTC, mathewseby commented on docs/ManualDeploymentGuideScalarDLonAzure.md
> +[Set up a database](./SetupAzureDatabase.md) for Scalar DL.
Fixed in 4c18add

2021-06-16 19:37 UTC, mathewseby commented on docs/ManualDeploymentGuideScalarDLonAzure.md
> +## Wipe out the Resources
Fixed in 4c18add

2021-06-16 19:37 UTC, mathewseby commented on docs/ManualDeploymentGuideScalarDLonAzure.md
> +### Confirm Database monitoring
Fixed in 4c18add

2021-06-16 19:37 UTC, mathewseby commented on docs/ManualDeploymentGuideScalarDLonAzure.md
> +If you want to remove the environment you can use the following section
Updated the sentence 

Fixed in 4c18add

2021-06-16 19:38 UTC, mathewseby commented on docs/ManualDeploymentGuideScalarDLonAzure.md
> +    $ helm delete load-schema
Changed `delete `commands to `uninstall` 
Fixed in 4c18add

2021-06-16 19:39 UTC, mathewseby commented on docs/ManualDeploymentGuideScalarDLonAzure.md
> +## Wipe out the Resources
Reorganized and updated the section.

Fixed in 4c18add

2021-06-16 19:39 UTC, mathewseby commented on docs/ManualDeploymentGuideScalarDLonAzure.md
> +* Remove the Resource group
Added steps to remove each resource.

Updated in 4c18add

2021-06-16 19:39 UTC, mathewseby commented on docs/SetupAzureDatabase.md
> +[Create an Azure Cosmos DB account](https://docs.microsoft.com/en-us/azure/cosmos-db/create-cosmosdb-resources-portal#create-an-azure-cosmos-db-account) with the above requirements.
Fixed in 4c18add

2021-06-16 19:40 UTC, mathewseby commented on docs/SetupAzureDatabase.md
> +### Procedures
Fixed in 4c18add

2021-06-16 19:40 UTC, mathewseby commented on docs/SetupAzureDatabase.md
> +To deploy Schema loading with CosmoDB, update the following configuration in [schema-loading-custom-values](https://github.com/scalar-labs/scalar-kubernetes/blob/master/conf/schema-loading-custom-val
Fixed in 4c18add

2021-06-16 19:40 UTC, mathewseby commented on docs/SetupAzureDatabase.md
> +To deploy Scalar DL with CosmosDB, update the following configuration in [scalardl-custom-values](https://github.com/scalar-labs/scalar-kubernetes/blob/master/conf/scalardl-custom-values.yaml)
Fixed in 4c18add

2021-06-16 19:40 UTC, mathewseby commented on docs/SetupAzureDatabase.md
> +
Added brief explanation in 4c18add

2021-06-16 19:41 UTC, mathewseby commented on docs/SetupAzureDatabase.md
> +You can scale the throughput of Cosmos DB by specifying cosmosBaseResourceUnit (which applies to all the tables) in [schema-loading-custom-values](https://github.com/scalar-labs/scalar-kubernetes/blo
Fixed in 4c18add

2021-06-16 19:41 UTC, mathewseby commented on docs/SetupAzureDatabase.md
> +
Added brief explanation in 4c18add

2021-06-16 19:41 UTC, mathewseby commented on docs/SetupAzureDatabase.md
> +More information can be found in [Monitor Azure Cosmos DB](https://docs.microsoft.com/en-us/azure/cosmos-db/monitor-cosmos-db) documentation.
Fixed in 4c18add

2021-06-16 19:42 UTC, mathewseby commented on docs/SetupAzureDatabase.md
> +#### Auto-scaling
Fixed in 4c18add

2021-06-16 19:42 UTC, mathewseby commented on docs/SetupAzureDatabase.md
> +You need to create a Cosmos DB account for Scalar DL. In this section, you will set up a Cosmos DB for Scalar DL.
Fixed in 4c18add

2021-06-16 19:49 UTC, mathewseby commented on docs/ManualDeploymentGuideScalarDLonAzure.md
> +* Azure monitor insights
Changed name to `Azure container insights`

Updated in 4c18add

2021-06-16 19:54 UTC, mathewseby commented on docs/ManualDeploymentGuideScalarDLonAzure.md
> +* Follow the [Maintain the cluster](./Maintaincluster.md) section for more customization.
Yes, the document is for customizing custom values for helm charts deployment. I have modified the sentence in 
ba30b7d

2021-06-16 19:55 UTC, mathewseby commented on docs/ManualDeploymentGuideScalarDLonAzure.md
> +    * [scalardl-custom-values.yaml](https://raw.githubusercontent.com/scalar-labs/scalar-kubernetes/master/conf/scalardl-custom-values.yaml)
Sorry, I couldn't get how to specify the files other than this one.

2021-06-16 19:56 UTC, mathewseby commented on docs/SetupAzureDatabase.md
> +Cosmos DB performance can be adjusted using the following parameters
Fixed in ba30b7d

2021-06-17 03:21 UTC, feeblefakie commented
@mathewseby I have updated directly for weird parts.

2021-06-17 03:27 UTC, feeblefakie commented
@mathewseby @scalar-boney I'll merge it for now. We can revise it as needed.

2021-06-17 03:27 UTC, merged