Fix link name in deployment guide
scalar-labs/scalar-kubernetes pull request #204
Opened 2023-07-21 05:57 UTC by kota2and3kan

This PR updates the link (document) name in the manual deployment guide based on the https://github.com/scalar-labs/scalar-kubernetes/pull/200#discussion_r1268854512 in another PR.

Please take a look!

2023-07-23 11:26 UTC, feeblefakie approved these changes
LGTM! Thank you!

2023-07-24 02:49 UTC, josh-wong requested changes
I've made a slight change to the doc titles and updated the link names. PTAL!

2023-07-24 02:49 UTC, josh-wong commented on docs/ManualDeploymentGuideScalarDBServerOnAKS.md
> +You must create an AKS cluster for the ScalarDB Server deployment. For details, see [A guideline for creating an AKS cluster for Scalar products](./CreateAKSClusterForScalarProducts.md).
```suggestion
You must create an AKS cluster for the ScalarDB Server deployment. For details, see [Guidelines for creating an AKS cluster for Scalar products](./CreateAKSClusterForScalarProducts.md).
```

2023-07-24 02:49 UTC, josh-wong commented on docs/ManualDeploymentGuideScalarDBServerOnEKS.md
> +You must create an EKS cluster for the ScalarDB Server deployment. For details, see [A guideline for creating an Amazon EKS cluster for Scalar products](./CreateEKSClusterForScalarProducts.md).
```suggestion
You must create an EKS cluster for the ScalarDB Server deployment. For details, see [Guidelines for creating an Amazon EKS cluster for Scalar products](./CreateEKSClusterForScalarProducts.md).
```

2023-07-24 02:49 UTC, josh-wong commented on docs/ManualDeploymentGuideScalarDLAuditorOnAKS.md
> +You must create an AKS cluster for the ScalarDL Ledger deployment. For details, see [A guideline for creating an AKS cluster for Scalar products](./CreateAKSClusterForScalarProducts.md).
```suggestion
You must create an AKS cluster for the ScalarDL Ledger deployment. For details, see [Guidelines for creating an AKS cluster for Scalar products](./CreateAKSClusterForScalarProducts.md).
```

2023-07-24 02:49 UTC, josh-wong commented on docs/ManualDeploymentGuideScalarDLAuditorOnAKS.md
> +You must also create an AKS cluster for the ScalarDL Auditor deployment. For details, see [A guideline for creating an AKS cluster for Scalar products](./CreateAKSClusterForScalarProducts.md).
```suggestion
You must also create an AKS cluster for the ScalarDL Auditor deployment. For details, see [Guidelines for creating an AKS cluster for Scalar products](./CreateAKSClusterForScalarProducts.md).
```

2023-07-24 02:49 UTC, josh-wong commented on docs/ManualDeploymentGuideScalarDLAuditorOnEKS.md
> +You must create an EKS cluster for the ScalarDL Ledger deployment. For details, see [A guideline for creating an Amazon EKS cluster for Scalar products](./CreateEKSClusterForScalarProducts.md).
```suggestion
You must create an EKS cluster for the ScalarDL Ledger deployment. For details, see [Guidelines for creating an Amazon EKS cluster for Scalar products](./CreateEKSClusterForScalarProducts.md).
```

2023-07-24 02:49 UTC, josh-wong commented on docs/ManualDeploymentGuideScalarDLAuditorOnEKS.md
> +You must also create an EKS cluster for the ScalarDL Auditor deployment. For details, see [A guideline for creating an Amazon EKS cluster for Scalar products](./CreateEKSClusterForScalarProducts.md).
```suggestion
You must also create an EKS cluster for the ScalarDL Auditor deployment. For details, see [Guidelines for creating an Amazon EKS cluster for Scalar products](./CreateEKSClusterForScalarProducts.md).
```

2023-07-24 02:49 UTC, josh-wong commented on docs/ManualDeploymentGuideScalarDLOnAKS.md
> +You must create an AKS cluster for the ScalarDL Ledger deployment. For details, see [A guideline for creating an AKS cluster for Scalar products](./CreateAKSClusterForScalarProducts.md).
```suggestion
You must create an AKS cluster for the ScalarDL Ledger deployment. For details, see [Guidelines for creating an AKS cluster for Scalar products](./CreateAKSClusterForScalarProducts.md).
```

2023-07-24 02:49 UTC, josh-wong commented on docs/ManualDeploymentGuideScalarDLOnEKS.md
> +You must create an EKS cluster for the ScalarDL Ledger deployment. For details, see [A guideline for creating an Amazon EKS cluster for Scalar products](./CreateEKSClusterForScalarProducts.md).
```suggestion
You must create an EKS cluster for the ScalarDL Ledger deployment. For details, see [Guidelines for creating an Amazon EKS cluster for Scalar products](./CreateEKSClusterForScalarProducts.md).
```

2023-07-26 07:26 UTC, kota2and3kan commented
@josh-wong  
Thank you for your review and suggestions!
I applied your suggestions. Please take a look when you have time!

2023-07-27 01:30 UTC, merged